### ISSUE TITLE
curl error "Not found"

### ISSUE THREAD

**Issue by yamaguchisota** [fisherman/install#1]
Please forgive my English, is not very good.

```sh
curl -sL install.fisherman.sh
```
```
Not found.
```

What can I do?

Thank you for your help.

**Comment by yamaguchisota** [comment]
I think it seems to be working fine now.

**Comment by bucaran** [comment]
Sorry about that, I had been messing with my DNS settings. Basically I changed the name of the installer from `installer.fish` to `install.fish`. I am glad is fixed for you now. 

Here is the current output:

<img width="517" alt="screen shot 2016-02-05 at 7 17 23 pm" src="https://cloud.githubusercontent.com/assets/8317250/12843511/3a62d8b2-cc3d-11e5-897f-830dcc78556e.png">
